export type FloorId = 1 | 2 | 3;

export interface Room {
  id: string;
  floorId: FloorId;
  number: string;
  name: string;
  type?: 'classroom' | 'office' | 'lab' | 'gym' | 'cafeteria';
  x: number; // координаты в системе карты
  y: number;
  width?: number; // размеры для прямоугольника
  height?: number;
  isFavorite?: boolean;
}

export const ROOMS: Room[] = [
  {
    id: '1',
    floorId: 1,
    number: '14',
    name: 'Кабинет для детей с особеностями',
    // type: 'classroom',
    x: 20,
    y: 18,
    width: 264,
    height: 164,
  },
  {
    id: '2',
    floorId: 1,
    number: '13',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 300,
    y: 18,
    width: 221,
    height: 164,
  },
  {
    id: '3',
    floorId: 1,
    number: '12',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 537,
    y: 18,
    width: 227,
    height: 164,
  },
  {
    id: '4',
    floorId: 1,
    number: '11',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 780,
    y: 18,
    width: 221,
    height: 164,
  },
  {
    id: '5',
    floorId: 1,
    number: '10',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 1017,
    y: 18,
    width: 224,
    height: 164,
  },
  {
    id: '6',
    floorId: 1,
    number: '9',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 1257,
    y: 18,
    width: 226,
    height: 164,
  },
  {
    id: '7',
    floorId: 1,
    number: '',
    name: 'Малый зал',
    // type: 'classroom',
    x: 20,
    y: 295,
    width: 198,
    height: 304,
  },
  {
    id: '8',
    floorId: 1,
    number: '16',
    name: 'Кабинет труда (Мальчики)',
    // type: 'classroom',
    x: 20,
    y: 613,
    width: 198,
    height: 244,
  },
  {
    id: '9',
    floorId: 1,
    number: '',
    name: 'Кабинет завуча',
    // type: 'classroom',
    x: 20,
    y: 869,
    width: 140,
    height: 85,
  },
  {
    id: '10',
    floorId: 1,
    number: '',
    name: 'Кабинет завуча',
    // type: 'classroom',
    x: 234,
    y: 857,
    width: 74,
    height: 95,
  },
  {
    id: '12',
    floorId: 1,
    number: 'Ж',
    name: 'Женский туалет',
    // type: 'classroom',
    x: 1499,
    y: 131,
    width: 57,
    height: 57,
  },
  {
    id: '13',
    floorId: 1,
    number: 'М',
    name: 'Мужской туалет',
    // type: 'classroom',
    x: 1610,
    y: 131,
    width: 56,
    height: 57,
  },
  {
    id: '14',
    floorId: 1,
    number: '8',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 1776,
    y: 18,
    width: 164,
    height: 250,
  },
  {
    id: '15',
    floorId: 1,
    number: '',
    name: 'Хол',
    // type: 'classroom',
    x: 1776,
    y: 288,
    width: 104,
    height: 301,
  },
  {
    id: '16',
    floorId: 1,
    number: '',
    name: 'Вахта',
    // type: 'classroom',
    x: 1890,
    y: 530,
    width: 50,
    height: 59,
  },
  {
    id: '17',
    floorId: 1,
    number: '',
    name: 'Буфет',
    // type: 'classroom',
    x: 1776,
    y: 601,
    width: 164,
    height: 231,
  },
  {
    id: '18',
    floorId: 1,
    number: '',
    name: 'Медицинский кабинет',
    // type: 'classroom',
    x: 1776,
    y: 849,
    width: 164,
    height: 72,
  },
  {
    id: '19',
    floorId: 1,
    number: '',
    name: 'Гардероб',
    // type: 'classroom',
    x: 1499,
    y: 358,
    width: 167,
    height: 71,
  },
  {
    id: '20',
    floorId: 1,
    number: '',
    name: 'Кухня',
    // type: 'classroom',
    x: 1499,
    y: 610,
    width: 167,
    height: 138,
  },
  {
    id: '21',
    floorId: 1,
    number: '',
    name: 'Столовая',
    // type: 'classroom',
    x: 1499,
    y: 766,
    width: 167,
    height: 339,
  },
  // Второй этаж 
  {
    id: '22',
    floorId: 2,
    number: '31',
    name: 'Кабинет математики',
    // type: 'classroom',
    x: 10,
    y: 20,
    width: 244,
    height: 190,
  },
  {
    id: '23',
    floorId: 2,
    number: '30',
    name: 'Кабинет математики',
    // type: 'classroom',
    x: 272,
    y: 20,
    width: 217,
    height: 190,
  },
  {
    id: '24',
    floorId: 2,
    number: '29',
    name: 'Кабинет русского языка и литературы',
    // type: 'classroom',
    x: 507,
    y: 20,
    width: 234,
    height: 190,
  },
  {
    id: '25',
    floorId: 2,
    number: '28',
    name: 'Кабинет биологии',
    // type: 'classroom',
    x: 759,
    y: 20,
    width: 231,
    height: 190,
  },
  {
    id: '26',
    floorId: 2,
    number: '27',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 1008,
    y: 20,
    width: 229,
    height: 190,
  },
  {
    id: '27',
    floorId: 2,
    number: '26',
    name: 'Кабинет начальных классов',
    // type: 'classroom',
    x: 1255,
    y: 20,
    width: 234,
    height: 190,
  },
  {
    id: '28',
    floorId: 2,
    number: '',
    name: 'Раздевалки',
    // type: 'classroom',
    x: 213,
    y: 330,
    width: 62,
    height: 155,
  },
  {
    id: '29',
    floorId: 2,
    number: 'Ж',
    name: 'Женская раздевалка',
    // type: 'classroom',
    x: 78,
    y: 330,
    width: 125,
    height: 75,
  },
  {
    id: '30',
    floorId: 2,
    number: 'М',
    name: 'Мужская раздевалка',
    // type: 'classroom',
    x: 78,
    y: 415,
    width: 125,
    height: 70,
  },
  {
    id: '31',
    floorId: 2,
    number: '',
    name: 'Большой зал',
    // type: 'classroom',
    x: 10,
    y: 495,
    width: 265,
    height: 573,
  },
  {
    id: '32',
    floorId: 2,
    number: 'М',
    name: 'Мужской туалет',
    // type: 'classroom',
    x: 1507,
    y: 154,
    width: 62,
    height: 60,
  },
  {
    id: '33',
    floorId: 2,
    number: 'Ж',
    name: 'Женский туалет',
    // type: 'classroom',
    x: 1616,
    y: 154,
    width: 63,
    height: 60,
  },
  {
    id: '34',
    floorId: 2,
    number: '25',
    name: 'Кабинет логопеда',
    // type: 'classroom',
    x: 1792,
    y: 20,
    width: 174,
    height: 290,
  },
  {
    id: '35',
    floorId: 2,
    number: '',
    name: 'Кабинет психолога',
    // type: 'classroom',
    x: 1792,
    y: 328,
    width: 174,
    height: 82,
  },
  {
    id: '36',
    floorId: 2,
    number: '24',
    name: 'Кабинет активистов',
    // type: 'classroom',
    x: 1792,
    y: 420,
    width: 174,
    height: 149,
  },
  {
    id: '37',
    floorId: 2,
    number: '22',
    name: 'Кабинет иностранного языка',
    // type: 'classroom',
    x: 1792,
    y: 587,
    width: 174,
    height: 171,
  },
  {
    id: '38',
    floorId: 2,
    number: '23',
    name: 'Кабинет иностранного языка',
    // type: 'classroom',
    x: 1792,
    y: 768,
    width: 174,
    height: 164,
  },
  {
    id: '39',
    floorId: 2,
    number: '',
    name: 'Приемная',
    // type: 'classroom',
    x: 1792,
    y: 950,
    width: 174,
    height: 81,
  },
  {
    id: '40',
    floorId: 2,
    number: '',
    name: 'Кабинет директора',
    // type: 'classroom',
    x: 1792,
    y: 1039,
    width: 174,
    height: 102,
  },
  {
    id: '41',
    floorId: 2,
    number: '',
    name: 'Библиотека',
    // type: 'classroom',
    x: 1507,
    y: 495,
    width: 173,
    height: 167,
  },
  {
    id: '42',
    floorId: 2,
    number: '21',
    name: 'Кабинет физики',
    // type: 'classroom',
    x: 1507,
    y: 855,
    width: 173,
    height: 282,
  },
  // Третий этаж
  {
    id: '43',
    floorId: 3,
    number: '41',
    name: 'Кабинет истории и обществознания',
    // type: 'classroom',
    x: 20,
    y: 20,
    width: 245,
    height: 181,
  },
  {
    id: '44',
    floorId: 3,
    number: '40',
    name: 'Кабинет русского языка и литературы',
    // type: 'classroom',
    x: 283,
    y: 20,
    width: 235,
    height: 181,
  },
  {
    id: '45',
    floorId: 3,
    number: '39',
    name: 'Кабинет ОБЗР',
    // type: 'classroom',
    x: 536,
    y: 20,
    width: 174,
    height: 181,
  },
  {
    id: '46',
    floorId: 3,
    number: '38',
    name: 'Кабинет математики',
    // type: 'classroom',
    x: 793,
    y: 20,
    width: 231,
    height: 181,
  },
  {
    id: '47',
    floorId: 3,
    number: '37',
    name: 'Кабинет русского языка',
    // type: 'classroom',
    x: 1042,
    y: 20,
    width: 235,
    height: 181,
  },
  {
    id: '48',
    floorId: 3,
    number: '36',
    name: 'Кабинет географии',
    // type: 'classroom',
    x: 1295,
    y: 20,
    width: 236,
    height: 181,
  },
  {
    id: '49',
    floorId: 3,
    number: '',
    name: 'Кабинет завуча',
    // type: 'classroom',
    x: 1549,
    y: 20,
    width: 73,
    height: 112,
  },
  {
    id: '50',
    floorId: 3,
    number: '',
    name: 'Кабинет завуча',
    // type: 'classroom',
    x: 1630,
    y: 20,
    width: 85,
    height: 112,
  },
  {
    id: '51',
    floorId: 3,
    number: '',
    name: 'Бухгалтерия',
    // type: 'classroom',
    x: 1831,
    y: 20,
    width: 176,
    height: 277,
  },
  {
    id: '52',
    floorId: 3,
    number: '',
    name: 'Актовый зал',
    // type: 'classroom',
    x: 1733,
    y: 317,
    width: 274,
    height: 550,
  },
  {
    id: '53',
    floorId: 3,
    number: '17',
    name: 'Кабинет трудов (Девочки)',
    // type: 'classroom',
    x: 1845,
    y: 974,
    width: 162,
    height: 186,
  },
  {
    id: '54',
    floorId: 3,
    number: '43',
    name: 'Кабинет химии',
    // type: 'classroom',
    x: 1549,
    y: 805,
    width: 164,
    height: 355,
  },
  {
    id: '55',
    floorId: 3,
    number: '35',
    name: 'Кабинет информатики',
    // type: 'classroom',
    x: 1549,
    y: 317,
    width: 164,
    height: 303,
  },
];